In [6]:

%pip install openpyxl

In [7]:

# CÉLULA 1 — Inspecionar as taxas de rendimento de 2025

from pathlib import Path
import pandas as pd

# Localizar a pasta do projeto
RAIZ = Path.cwd()

if RAIZ.name == "notebooks":
    RAIZ = RAIZ.parent

arquivo_taxas = (
    RAIZ / "dados-brutos" / "tx_rend_escolas_2025.xlsx"
)

if not arquivo_taxas.exists():
    raise FileNotFoundError(
        f"Arquivo não encontrado: {arquivo_taxas}\n"
        "Confira a pasta dados-brutos."
    )

# Listar as abas do Excel
xls = pd.ExcelFile(arquivo_taxas)

print("Abas disponíveis:")
print(xls.sheet_names)

# Inspecionar as primeiras linhas de cada aba
for aba in xls.sheet_names:
    dados_aba = pd.read_excel(
        arquivo_taxas,
        sheet_name=aba,
        nrows=5
    )

    print(f"\n=== Aba: {aba} ===")
    print("Colunas:")
    print(dados_aba.columns.tolist())

    display(dados_aba.head())

Abas disponíveis:
['ESCOLAS']

=== Aba: ESCOLAS ===
Colunas:
['Unnamed: 0', 'Ministério da Educação', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45']

,Unnamed: 0,Ministério da Educação,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,NaN,Instituto Nacional de Estudos e Pesquisas Educ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Taxas de Rendimento Escolar (Aprovação, Reprov...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localização,Dependência Administrativa,Taxa de Aprovação,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Taxa de Abandono

In [8]:

# CÉLULA 2 — Ler o Excel com o cabeçalho correto

arquivo_taxas = RAIZ / "dados-brutos" / "tx_rend_escolas_2025.xlsx"

df_taxas = pd.read_excel(
    arquivo_taxas,
    sheet_name="ESCOLAS",
    header=4
)

# Remover colunas totalmente vazias
df_taxas = df_taxas.dropna(axis=1, how="all")

# Remover espaços dos nomes das colunas
df_taxas.columns = (
    df_taxas.columns
    .astype(str)
    .str.strip()
)

print("Dimensões:", df_taxas.shape)

print("\nColunas disponíveis:")
for coluna in df_taxas.columns:
    print("-", coluna)

print("\nPrimeiras linhas:")
display(df_taxas.head())

print("\nValores ausentes por coluna:")
display(
    df_taxas.isna().sum()
    .sort_values(ascending=False)
    .to_frame("valores_ausentes")
)

Dimensões: (126690, 63)

Colunas disponíveis:
- Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2025
- Unnamed: 1
- Unnamed: 2
- Unnamed: 3
- Unnamed: 4
- Unnamed: 5
- Unnamed: 6
- Unnamed: 7
- Unnamed: 8
- Unnamed: 9
- Unnamed: 10
- Unnamed: 11
- Unnamed: 12
- Unnamed: 13
- Unnamed: 14
- Unnamed: 15
- Unnamed: 16
- Unnamed: 17
- Unnamed: 18
- Unnamed: 19
- Unnamed: 20
- Unnamed: 21
- Unnamed: 22
- Unnamed: 23
- Unnamed: 24
- Unnamed: 25
- Unnamed: 26
- Unnamed: 27
- Unnamed: 28
- Unnamed: 29
- Unnamed: 30
- Unnamed: 31
- Unnamed: 32
- Unnamed: 33
- Unnamed: 34
- Unnamed: 35
- Unnamed: 36
- Unnamed: 37
- Unnamed: 38
- Unnamed: 39
- Unnamed: 40
- Unnamed: 41
- Unnamed: 42
- Unnamed: 43
- Unnamed: 44
- Unnamed: 45
- Unnamed: 46
- Unnamed: 47
- Unnamed: 48
- Unnamed: 49
- Unnamed: 50
- Unnamed: 51
- Unnamed: 52
- Unnamed: 53
- Unnamed: 54
- Unnamed: 55
- Unnamed: 56
- Unnamed: 57
- Unnamed: 58
- Unnamed: 59
- Unnamed: 60
- Unnamed: 61
- Unnamed: 62

Primeiras linhas:

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2025",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,Ano,Região,UF,Código do Município,Nome do Município,Código da Escola,Nome da Escola,Localização,Dependência Administrativa,Taxa de Aprovação,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ensino Fundamental de 8 e 9 anos,...,NaN,NaN,NaN,NaN,Ensino Médio,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,...,6º Ano,7º Ano,8º Ano,9º Ano,Total,1ª série,2ª série,3ª série,4ª série,Não-Seriado
3,NU_ANO_CENSO,NO_REGIAO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,CO_ENTIDADE,NO_ENTIDADE,NO_CATEGORIA,NO_DEPENDENCIA,1_CAT_FUN,...,3_CAT_FUN_06,3_CAT_FUN_07,3_CAT_FUN_08,3_CAT_FUN_09,3_CAT_MED,3_CAT_MED_01,3_CAT_MED_02,3_CAT_MED_03,3_CAT_MED_04,3_CAT_MED_NS
4,2025,Norte,RO,1100015,Alta Floresta D'Oeste,11022558,EIEEF HAP BITT TUPARI,Rural,Estadual,100,...,--,--,--,--,--,--,--,--,--,--

Valores ausentes por coluna:

             valores_ausentes
Unnamed: 1                  4
Unnamed: 2                  4
Unnamed: 3                  4
Unnamed: 5                  4
Unnamed: 4                  4
...                       ...
Unnamed: 21                 3
Unnamed: 57                 3
Unnamed: 9                  2
Unnamed: 27                 2
Unnamed: 45                 2

[63 rows x 1 columns]

In [9]:

# CÉLULA 3 — Corrigir cabeçalho e limpar linhas iniciais

arquivo_taxas = RAIZ / "dados-brutos" / "tx_rend_escolas_2025.xlsx"

# A linha com os nomes técnicos é a linha de índice 3
df_taxas = pd.read_excel(
    arquivo_taxas,
    sheet_name="ESCOLAS",
    header=3
)

# Remover colunas sem nome técnico
df_taxas = df_taxas.loc[
    :,
    ~df_taxas.columns.astype(str).str.startswith("Unnamed")
].copy()

# Remover espaços dos nomes das colunas
df_taxas.columns = (
    df_taxas.columns.astype(str).str.strip()
)

# Remover linhas sem código da entidade escolar
if "CO_ENTIDADE" in df_taxas.columns:
    df_taxas = df_taxas[
        df_taxas["CO_ENTIDADE"].notna()
    ].copy()

print("Dimensões após ajuste:", df_taxas.shape)

print("\nColunas disponíveis:")
for coluna in df_taxas.columns:
    print("-", coluna)

print("\nColunas relacionadas a abandono:")
print([
    coluna for coluna in df_taxas.columns
    if "ABAND" in coluna.upper()
])

print("\nAmostra:")
display(df_taxas.head())

Dimensões após ajuste: (126691, 1)

Colunas disponíveis:
- Taxas de Rendimento Escolar por escola - 2025

Colunas relacionadas a abandono:
[]

Amostra:

       Taxas de Rendimento Escolar por escola - 2025
0  Taxas de Rendimento Escolar (Aprovação, Reprov...
1                                                Ano
2                                                NaN
3                                                NaN
4                                       NU_ANO_CENSO

In [10]:

# CÉLULA 4 — Ler corretamente as taxas de rendimento

arquivo_taxas = RAIZ / "dados-brutos" / "tx_rend_escolas_2025.xlsx"

df_taxas = pd.read_excel(
    arquivo_taxas,
    sheet_name="ESCOLAS",
    header=8
)

# Remover colunas totalmente vazias
df_taxas = df_taxas.dropna(axis=1, how="all")

# Remover espaços dos nomes
df_taxas.columns = df_taxas.columns.astype(str).str.strip()

# Manter somente linhas que identificam uma escola
df_taxas = df_taxas[
    df_taxas["CO_ENTIDADE"].notna()
].copy()

print("Dimensões:", df_taxas.shape)

print("\nColunas de identificação:")
display(df_taxas[
    [
        "NU_ANO_CENSO",
        "SG_UF",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "CO_ENTIDADE",
        "NO_ENTIDADE"
    ]
].head())

print("\nColunas de taxas do ensino médio:")
print([c for c in df_taxas.columns if "MED" in c])

print("\nAmostra das taxas do ensino médio:")
display(
    df_taxas[
        ["NU_ANO_CENSO", "SG_UF", "CO_ENTIDADE",
         "1_CAT_MED", "2_CAT_MED", "3_CAT_MED"]
    ].head()
)

Dimensões: (126684, 63)

Colunas de identificação:

,NU_ANO_CENSO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,CO_ENTIDADE,NO_ENTIDADE
0,2025,RO,1100015.0,Alta Floresta D'Oeste,11022558.0,EIEEF HAP BITT TUPARI
1,2025,RO,1100015.0,Alta Floresta D'Oeste,11024372.0,EMEIEF ANA NERY
2,2025,RO,1100015.0,Alta Floresta D'Oeste,11024666.0,EMEIEF BOA ESPERANCA
3,2025,RO,1100015.0,Alta Floresta D'Oeste,11024682.0,EEEFM EURIDICE LOPES PEDROSO
4,2025,RO,1100015.0,Alta Floresta D'Oeste,11024828.0,EMEIEF IZIDORO STEDILE

Colunas de taxas do ensino médio:
['1_CAT_MED', '1_CAT_MED_01', '1_CAT_MED_02', '1_CAT_MED_03', '1_CAT_MED_04', '1_CAT_MED_NS', '2_CAT_MED', '2_CAT_MED_01', '2_CAT_MED_02', '2_CAT_MED_03', '2_CAT_MED_04', '2_CAT_MED_NS', '3_CAT_MED', '3_CAT_MED_01', '3_CAT_MED_02', '3_CAT_MED_03', '3_CAT_MED_04', '3_CAT_MED_NS']

Amostra das taxas do ensino médio:

  NU_ANO_CENSO SG_UF  CO_ENTIDADE 1_CAT_MED 2_CAT_MED 3_CAT_MED
0         2025    RO   11022558.0        --        --        --
1         2025    RO   11024372.0        --        --        --
2         2025    RO   11024666.0        --        --        --
3         2025    RO   11024682.0      99.7       0.3         0
4         2025    RO   11024828.0        --        --        --

In [11]:

# CÉLULA 5 — Filtrar escolas da Paraíba

# Garantir que os códigos de identificação tenham tipos consistentes
df_taxas["SG_UF"] = df_taxas["SG_UF"].astype(str).str.strip()

# Filtrar registros da Paraíba
df_pb = df_taxas[df_taxas["SG_UF"] == "PB"].copy()

print("Total de registros no Brasil:", len(df_taxas))
print("Registros da Paraíba:", len(df_pb))

print("\nDistribuição por ano:")
display(df_pb["NU_ANO_CENSO"].value_counts(dropna=False))

print("\nDistribuição por dependência administrativa:")
display(df_pb["NO_DEPENDENCIA"].value_counts(dropna=False))

print("\nColunas das taxas do ensino médio:")
colunas_medio = [
    c for c in df_pb.columns
    if "CAT_MED" in c
]

print(colunas_medio)

print("\nAmostra das escolas da Paraíba:")
display(
    df_pb[
        [
            "NU_ANO_CENSO",
            "SG_UF",
            "CO_MUNICIPIO",
            "NO_MUNICIPIO",
            "CO_ENTIDADE",
            "NO_ENTIDADE",
            "NO_DEPENDENCIA",
            "1_CAT_MED",
            "2_CAT_MED",
            "3_CAT_MED"
        ]
    ].head(10)
)

Total de registros no Brasil: 126684
Registros da Paraíba: 3782

Distribuição por ano:

NU_ANO_CENSO
2025    3782
Name: count, dtype: int64

Distribuição por dependência administrativa:

NO_DEPENDENCIA
Municipal    2340
Privada       838
Estadual      583
Federal        21
Name: count, dtype: int64

Colunas das taxas do ensino médio:
['1_CAT_MED', '1_CAT_MED_01', '1_CAT_MED_02', '1_CAT_MED_03', '1_CAT_MED_04', '1_CAT_MED_NS', '2_CAT_MED', '2_CAT_MED_01', '2_CAT_MED_02', '2_CAT_MED_03', '2_CAT_MED_04', '2_CAT_MED_NS', '3_CAT_MED', '3_CAT_MED_01', '3_CAT_MED_02', '3_CAT_MED_03', '3_CAT_MED_04', '3_CAT_MED_NS']

Amostra das escolas da Paraíba:

,NU_ANO_CENSO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,CO_ENTIDADE,NO_ENTIDADE,NO_DEPENDENCIA,1_CAT_MED,2_CAT_MED,3_CAT_MED
40156,2025,PB,2500106.0,Água Branca,25033158.0,EMEIF MAE IAIA,Municipal,--,--,--
40157,2025,PB,2500106.0,Água Branca,25033204.0,ECI JOSE NOMINANDO,Estadual,92.2,1.3,6.5
40158,2025,PB,2500106.0,Água Branca,25033425.0,EMEF SEVERINO FIRMINO DE SANTANA,Municipal,--,--,--
40159,2025,PB,2500106.0,Água Branca,25033476.0,EMEF ANDRE ALVES DO NASCIMENTO,Municipal,--,--,--
40160,2025,PB,2500106.0,Água Branca,25033514.0,EMEF JOSE GOMES DE SALES,Municipal,--,--,--
40161,2025,PB,2500106.0,Água Branca,25033549.0,EMEF AUGUSTO DOS ANJOS,Municipal,--,--,--
40162,2025,PB,2500106.0,Água Branca,25033557.0,EMEIF DELFINO JOSE DOS SANTOS,Municipal,--,--,--
40163,2025,PB,2500106.0,Água Branca,25033573.0,EMEF FRANCISCO LOPES DA SILVA,Municipal,--,--,--
40164,2025,PB,2500106.0,Água Branca,25033654.0,EMEF MANOEL GONCALVES DE MOURA,Municipal,--,--,--
40165,2025,PB,2500106.0,Água Branca,25033670.0,EMEF ANTONIO VIRGOLINO BATISTA,Municipal,--,--,--

In [12]:

# CÉLULA 6 — Preparar a base de abandono do ensino médio público

# Manter escolas públicas da Paraíba
df_publicas = df_pb[
    df_pb["NO_DEPENDENCIA"].isin(["Municipal", "Estadual", "Federal"])
].copy()

# Converter os códigos de taxa para valores numéricos.
# Os símbolos "--" serão considerados ausentes, não como zero.
colunas_taxas = ["1_CAT_MED", "2_CAT_MED", "3_CAT_MED"]

for coluna in colunas_taxas:
    df_publicas[coluna] = pd.to_numeric(
        df_publicas[coluna].replace("--", pd.NA),
        errors="coerce"
    )

print("Escolas públicas na Paraíba:", len(df_publicas))

print("\nDisponibilidade das taxas do ensino médio:")
display(
    df_publicas[colunas_taxas].isna().sum()
    .rename("valores_ausentes")
    .to_frame()
    .assign(
        percentual_ausente=lambda x:
        (x["valores_ausentes"] / len(df_publicas) * 100).round(2)
    )
)

# Registros com taxa de abandono disponível
df_abandono = df_publicas[
    df_publicas["3_CAT_MED"].notna()
].copy()

print("\nRegistros públicos com taxa de abandono disponível:",
      len(df_abandono))

print("\nResumo da taxa de abandono:")
display(df_abandono["3_CAT_MED"].describe())

print("\nAmostra:")
display(
    df_abandono[
        [
            "NU_ANO_CENSO",
            "SG_UF",
            "CO_MUNICIPIO",
            "NO_MUNICIPIO",
            "CO_ENTIDADE",
            "NO_ENTIDADE",
            "NO_DEPENDENCIA",
            "3_CAT_MED"
        ]
    ].head(10)
)

Escolas públicas na Paraíba: 2944

Disponibilidade das taxas do ensino médio:

           valores_ausentes  percentual_ausente
1_CAT_MED              2435               82.71
2_CAT_MED              2435               82.71
3_CAT_MED              2435               82.71

Registros públicos com taxa de abandono disponível: 509

Resumo da taxa de abandono:

count    509.000000
mean       3.473084
std        4.054618
min        0.000000
25%        0.200000
50%        2.000000
75%        5.500000
max       21.000000
Name: 3_CAT_MED, dtype: float64

Amostra:

,NU_ANO_CENSO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,CO_ENTIDADE,NO_ENTIDADE,NO_DEPENDENCIA,3_CAT_MED
40157,2025,PB,2500106.0,Água Branca,25033204.0,ECI JOSE NOMINANDO,Estadual,6.5
40169,2025,PB,2500205.0,Aguiar,25023489.0,ECI EEM AGENOR MENDES PEDROSA,Estadual,0.0
40174,2025,PB,2500304.0,Alagoa Grande,25062638.0,EEEFM PADRE HILDON BANDEIRA,Estadual,3.7
40178,2025,PB,2500304.0,Alagoa Grande,25062816.0,ECIT OSWALDO TRIGUEIRO DE ALBUQUERQUE MELO,Estadual,0.0
40212,2025,PB,2500403.0,Alagoa Nova,25063340.0,ECIT MONSENHOR JOSE BORGES DE CARVALHO,Estadual,2.8
40213,2025,PB,2500403.0,Alagoa Nova,25063421.0,EEEFM PROFESSOR CARDOSO,Estadual,3.3
40236,2025,PB,2500502.0,Alagoinha,25066374.0,ECIT AGENOR CLEMENTE DOS SANTOS,Estadual,0.2
40248,2025,PB,2500536.0,Alcantil,25051598.0,ECIT PROFESSORA MARIA CECILIA DE CASTRO,Estadual,4.1
40259,2025,PB,2500577.0,Algodão de Jandaíra,25152823.0,ECI EUCLIDES MOUZINHO DOS SANTOS,Estadual,4.1
40260,2025,PB,2500601.0,Alhandra,25100033.0,ECIT RENATO RIBEIRO COUTINHO,Estadual,4.0

In [13]:

# CÉLULA 7 — Salvar a base de taxas da Paraíba

from pathlib import Path

# Selecionar os campos necessários
colunas = [
    "NU_ANO_CENSO",
    "SG_UF",
    "CO_MUNICIPIO",
    "NO_MUNICIPIO",
    "CO_ENTIDADE",
    "NO_ENTIDADE",
    "NO_DEPENDENCIA",
    "1_CAT_MED",
    "2_CAT_MED",
    "3_CAT_MED"
]

# Manter escolas públicas com taxa de abandono disponível
base_taxas_pb = df_abandono[colunas].copy()

# Padronizar nomes das colunas
base_taxas_pb = base_taxas_pb.rename(columns={
    "NU_ANO_CENSO": "ano",
    "SG_UF": "uf",
    "CO_MUNICIPIO": "codigo_municipio",
    "NO_MUNICIPIO": "municipio",
    "CO_ENTIDADE": "codigo_escola",
    "NO_ENTIDADE": "nome_escola",
    "NO_DEPENDENCIA": "dependencia",
    "1_CAT_MED": "taxa_aprovacao_medio",
    "2_CAT_MED": "taxa_reprovacao_medio",
    "3_CAT_MED": "taxa_abandono_medio"
})

# Salvar o resultado
pasta_saida = RAIZ / "dados" / "processado"
pasta_saida.mkdir(parents=True, exist_ok=True)

arquivo_saida = pasta_saida / "taxas_abandono_pb_2025.csv"

base_taxas_pb.to_csv(
    arquivo_saida,
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo:", arquivo_saida)
print("Total de registros:", len(base_taxas_pb))
print("Escolas únicas:", base_taxas_pb["codigo_escola"].nunique())

display(base_taxas_pb.head())

Arquivo salvo: c:\Users\Maria\Downloads\projeto-evasao\dados\processado\taxas_abandono_pb_2025.csv
Total de registros: 509
Escolas únicas: 509

,ano,uf,codigo_municipio,municipio,codigo_escola,nome_escola,dependencia,taxa_aprovacao_medio,taxa_reprovacao_medio,taxa_abandono_medio
40157,2025,PB,2500106.0,Água Branca,25033204.0,ECI JOSE NOMINANDO,Estadual,92.2,1.3,6.5
40169,2025,PB,2500205.0,Aguiar,25023489.0,ECI EEM AGENOR MENDES PEDROSA,Estadual,100.0,0.0,0.0
40174,2025,PB,2500304.0,Alagoa Grande,25062638.0,EEEFM PADRE HILDON BANDEIRA,Estadual,95.3,1.0,3.7
40178,2025,PB,2500304.0,Alagoa Grande,25062816.0,ECIT OSWALDO TRIGUEIRO DE ALBUQUERQUE MELO,Estadual,99.4,0.6,0.0
40212,2025,PB,2500403.0,Alagoa Nova,25063340.0,ECIT MONSENHOR JOSE BORGES DE CARVALHO,Estadual,94.8,2.4,2.8